spring:
  application:
    name: SpringBootJpaSecurityHW
  datasource:
    url: jdbc:postgresql://localhost:5432/SpringBootJpaSecurityHillel
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
    hibernate:
      ddl-auto: validate
    show-sql: true